spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/minha_vacina
    username: tcc
    password: 123456


  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  senha: NzBjZDlkN2YtNjdkMC00NWU5LThmZmQtNmEzY2JlMzQwZDMy
  expiracao: 864000000